sf_guard_user_profile:
  _attributes: { phpName: sfGuardUserProfile }
  id:
  user_id:     { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
  facebook_id { type: integer }
  first_name:  varchar(30)
  last_name:   varchar(30)
  email:       varchar(255)
  website:     varchar(255)
  phone:       varchar(255)