<?php



/**
 * This class defines the structure of the 'user' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sun May 19 13:05:12 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class UserTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.UserTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('user');
        $this->setPhpName('User');
        $this->setClassname('User');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('FACEBOOK_ID', 'FacebookId', 'BIGINT', false, null, null);
        $this->addColumn('FIRST_NAME', 'FirstName', 'VARCHAR', false, 255, null);
        $this->addColumn('LAST_NAME', 'LastName', 'VARCHAR', false, 255, null);
        $this->addColumn('GENDER', 'Gender', 'BOOLEAN', false, 1, false);
        $this->addColumn('EMAIL', 'Email', 'VARCHAR', false, 255, null);
        $this->addColumn('BIRTHSDAY', 'Birthsday', 'VARCHAR', false, 255, null);
        $this->addColumn('PHONE', 'Phone', 'VARCHAR', false, 255, null);
        $this->addColumn('LAST_IP', 'LastIp', 'VARCHAR', false, 45, null);
        $this->addColumn('IS_SECURED', 'IsSecured', 'BOOLEAN', false, 1, null);
        $this->addColumn('LONG_TOKEN', 'LongToken', 'VARCHAR', false, 255, null);
        $this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('FriendRelatedByUserId', 'Friend', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null, 'FriendsRelatedByUserId');
        $this->addRelation('FriendRelatedByFriendId', 'Friend', RelationMap::ONE_TO_MANY, array('id' => 'friend_id', ), null, null, 'FriendsRelatedByFriendId');
        $this->addRelation('Page', 'Page', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null, 'Pages');
        $this->addRelation('UserEvent', 'UserEvent', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null, 'UserEvents');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
            'symfony_timestampable' => array('update_column' => 'updated_at', 'create_column' => 'created_at', ),
        );
    } // getBehaviors()

} // UserTableMap
