generator:
  class: sfPropelGenerator
  param:
    model_class:           Answer
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Answer
    plural:                Answers
    route_prefix:          answer
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
