<?php



/**
 * Skeleton subclass for performing query and update operations on the 'page' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sat May 18 13:22:50 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class PagePeer extends BasePagePeer
{

	public static function getPages() {
		$c = new Criteria();
		return self::doSelect($c);
	}

	public static function parsePages() {
		$pages = self::getPages();
		$events = array();
		foreach($pages as $page) {
			$eventsList = Facebook::get()->getPageEvents($page->getFacebookId(), $page->getAccessToken());
			$events = array();

			foreach ($eventsList as $_event) {
				$_event = Facebook::get()->getEvent($_event['id'], $page->getAccessToken());

				$event = new Event();
				if(isset($_event['name']))
					$event->setName($_event['name']);

				if(isset($_event['start_time']))
					$event->setStart($_event['start_time']);

				if(isset($_event['end_time']))
					$event->setEnd($_event['end_time']);

				if(isset($_event['timezone']))
					$event->setTimezone($_event['timezone']);

				if(isset($_event['location']))
					$event->setLocation($_event['location']);

				if(isset($_event['id']))
					$event->setFacebookId($_event['id']);

				if(isset($_event['id']))
					$event->setPicture("http://graph.facebook.com/".$_event['id']."/picture");

				if(isset($_event['description']))
					$event->setDescription($_event['description']);

				if(isset($_event['venue'])) {
					$event->setIsFollow(in_array(Facebook::get()->getUser()->getFacebookId(), $_event['venue']));
				}

			
				$event->setPage($page);
				$event->setIsPublic(true);


				$invited = Facebook::get()->getInvited($event->getFacebookId(), $event->getPage()->getAccessToken());
				if(isset($invited['data'])) {
					foreach ($invited['data'] as $key => $value) {
						if($value['id'] == Facebook::get()->getUser()->getFacebookId() && $value['rsvp_status'] == 'attending') {
							$event->setIsFollow(true);
							$event->setIsInvited(true);
						} elseif($value['id'] == Facebook::get()->getUser()->getFacebookId()) {
							$event->setIsInvited(true);
						}
						
					}	
				}

				$event->setFoundation($page->getFoundation());

				$events[] = $event;
			}
		}
		return $events;
	}

	public static function getByFacebookId($id) {
		if(is_null($id))
			return null;
		
		$c = new Criteria();
		$c->add(self::FACEBOOK_ID, $id);
		$row = self::doSelectOne($c);
		return $row;
	} 

}
