<?php



/**
 * Skeleton subclass for representing a row from the 'user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Sat Jan  5 11:53:55 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class User extends BaseUser {
	
	public function __toString() {
		return $this->getEmail();
	}
} // User
